### PR TITLE
Update CCUD Gradle plugin to 1.9

### PR DESCRIPTION
**Pull request by jprinet**

### CODE REVIEW

**Comment by etiennestuder** [comment]
@dependabot rebase

**Comment by etiennestuder** [comment]
@jprinet would you mind rebasing to latest HEAD given the various GE version upgrades? Thanks.

**Comment by jprinet** [comment]
> @jprinet would you mind rebasing to latest HEAD given the various GE version upgrades? Thanks.

Just did @etiennestuder 👍

**Comment by etiennestuder** [comment]
Thanks, @jprinet

**Pull request merged**
